"use client"

import { useState } from "react"
import jsPDF from "jspdf"

interface Tweet {
  id: string
  text: string
  likes: number
  retweets: number
  replies: number
  impressions?: number
  date: string
  url?: string
}

export default function TweetManager() {
  const [tweets, setTweets] = useState<Tweet[]>([])
  const [newTweet, setNewTweet] = useState({
    text: "",
    likes: 0,
    retweets: 0,
    replies: 0,
    impressions: 0,
    url: "",
  })
  const [isExporting, setIsExporting] = useState(false)
  const [showAddForm, setShowAddForm] = useState(false)

  const addTweet = () => {
    if (!newTweet.text.trim()) {
      alert("Please enter tweet text")
      return
    }

    const tweet: Tweet = {
      id: Date.now().toString(),
      text: newTweet.text,
      likes: newTweet.likes,
      retweets: newTweet.retweets,
      replies: newTweet.replies,
      impressions: newTweet.impressions || undefined,
      date: new Date().toISOString().split("T")[0],
      url: newTweet.url || undefined,
    }

    setTweets([...tweets, tweet])
    setNewTweet({
      text: "",
      likes: 0,
      retweets: 0,
      replies: 0,
      impressions: 0,
      url: "",
    })
    setShowAddForm(false)
  }

  const removeTweet = (id: string) => {
    setTweets(tweets.filter((t) => t.id !== id))
  }

  const exportToPDF = async () => {
    if (tweets.length === 0) {
      alert("No tweets to export")
      return
    }

    setIsExporting(true)

    try {
      const pdf = new jsPDF("p", "mm", "a4")
      const pageWidth = pdf.internal.pageSize.getWidth()
      const pageHeight = pdf.internal.pageSize.getHeight()
      const margin = 20
      const contentWidth = pageWidth - 2 * margin
      let yPosition = margin

      // Title
      pdf.setFontSize(24)
      pdf.setFont("helvetica", "bold")
      pdf.text("Top Performing Tweets", margin, yPosition)
      yPosition += 15

      // Subtitle
      pdf.setFontSize(12)
      pdf.setFont("helvetica", "normal")
      pdf.setTextColor(100, 100, 100)
      pdf.text(`Generated on ${new Date().toLocaleDateString()}`, margin, yPosition)
      pdf.text(`Total Tweets: ${tweets.length}`, pageWidth - margin - 40, yPosition)
      yPosition += 15

      // Summary stats
      const totalLikes = tweets.reduce((sum, t) => sum + t.likes, 0)
      const totalRetweets = tweets.reduce((sum, t) => sum + t.retweets, 0)
      const totalImpressions = tweets.reduce((sum, t) => sum + (t.impressions || 0), 0)

      pdf.setFontSize(10)
      pdf.setTextColor(0, 0, 0)
      pdf.text(`Total Engagement: ${totalLikes} likes, ${totalRetweets} retweets`, margin, yPosition)
      if (totalImpressions > 0) {
        pdf.text(`Total Impressions: ${totalImpressions.toLocaleString()}`, margin, yPosition + 5)
        yPosition += 5
      }
      yPosition += 15

      // Add each tweet
      for (let i = 0; i < tweets.length; i++) {
        const tweet = tweets[i]

        // Check if we need a new page
        if (yPosition > pageHeight - 60) {
          pdf.addPage()
          yPosition = margin
        }

        // Tweet number and date
        pdf.setFontSize(12)
        pdf.setFont("helvetica", "bold")
        pdf.setTextColor(29, 161, 242) // Twitter blue
        pdf.text(`Tweet #${i + 1}`, margin, yPosition)
        pdf.setFont("helvetica", "normal")
        pdf.setFontSize(9)
        pdf.setTextColor(100, 100, 100)
        pdf.text(tweet.date, pageWidth - margin - 30, yPosition)
        yPosition += 7

        // Tweet text
        pdf.setFontSize(10)
        pdf.setTextColor(0, 0, 0)
        const lines = pdf.splitTextToSize(tweet.text, contentWidth)
        pdf.text(lines, margin, yPosition)
        yPosition += lines.length * 5 + 5

        // Metrics box
        pdf.setFillColor(240, 240, 240)
        pdf.rect(margin, yPosition, contentWidth, 12, "F")

        pdf.setFontSize(9)
        pdf.setTextColor(50, 50, 50)
        const metricsY = yPosition + 8
        pdf.text(`♥ ${tweet.likes}`, margin + 5, metricsY)
        pdf.text(`⟳ ${tweet.retweets}`, margin + 35, metricsY)
        pdf.text(`💬 ${tweet.replies}`, margin + 65, metricsY)
        if (tweet.impressions) {
          pdf.text(`👁 ${tweet.impressions.toLocaleString()}`, margin + 95, metricsY)
        }

        yPosition += 15

        // URL if available
        if (tweet.url) {
          pdf.setFontSize(8)
          pdf.setTextColor(29, 161, 242)
          pdf.textWithLink("View Tweet", margin, yPosition, { url: tweet.url })
          yPosition += 5
        }

        yPosition += 5 // Space between tweets
      }

      // Footer on last page
      pdf.setFontSize(8)
      pdf.setTextColor(150, 150, 150)
      pdf.text(
        "Generated by xcampBanana - Personal Brand Kit",
        pageWidth / 2,
        pageHeight - 10,
        { align: "center" }
      )

      // Save PDF
      pdf.save(`top-performing-tweets-${new Date().toISOString().split("T")[0]}.pdf`)
    } catch (error) {
      console.error("PDF export error:", error)
      alert("Failed to export PDF. Please try again.")
    } finally {
      setIsExporting(false)
    }
  }

  const calculateEngagementRate = (tweet: Tweet) => {
    if (!tweet.impressions || tweet.impressions === 0) return "N/A"
    const engagement = tweet.likes + tweet.retweets + tweet.replies
    const rate = (engagement / tweet.impressions) * 100
    return `${rate.toFixed(2)}%`
  }

  return (
    <div className="w-full">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h2 className="text-2xl font-bold">Top Performing Tweets</h2>
          <p className="text-gray-600 mt-1">
            Track and export your best-performing tweets
          </p>
        </div>
        <div className="flex gap-3">
          <button
            onClick={() => setShowAddForm(!showAddForm)}
            className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            {showAddForm ? "Cancel" : "Add Tweet"}
          </button>
          {tweets.length > 0 && (
            <button
              onClick={exportToPDF}
              disabled={isExporting}
              className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors disabled:bg-gray-400"
            >
              {isExporting ? "Exporting..." : "Export to PDF"}
            </button>
          )}
        </div>
      </div>

      {showAddForm && (
        <div className="mb-6 p-6 bg-white rounded-lg border-2 border-gray-200 shadow-sm">
          <h3 className="text-lg font-semibold mb-4">Add New Tweet</h3>
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Tweet Text *
              </label>
              <textarea
                value={newTweet.text}
                onChange={(e) => setNewTweet({ ...newTweet, text: e.target.value })}
                placeholder="Enter your tweet text..."
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                rows={4}
              />
            </div>

            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Likes
                </label>
                <input
                  type="number"
                  value={newTweet.likes}
                  onChange={(e) => setNewTweet({ ...newTweet, likes: parseInt(e.target.value) || 0 })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
                  min="0"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Retweets
                </label>
                <input
                  type="number"
                  value={newTweet.retweets}
                  onChange={(e) => setNewTweet({ ...newTweet, retweets: parseInt(e.target.value) || 0 })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
                  min="0"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Replies
                </label>
                <input
                  type="number"
                  value={newTweet.replies}
                  onChange={(e) => setNewTweet({ ...newTweet, replies: parseInt(e.target.value) || 0 })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
                  min="0"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Impressions
                </label>
                <input
                  type="number"
                  value={newTweet.impressions}
                  onChange={(e) => setNewTweet({ ...newTweet, impressions: parseInt(e.target.value) || 0 })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
                  min="0"
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Tweet URL (optional)
              </label>
              <input
                type="url"
                value={newTweet.url}
                onChange={(e) => setNewTweet({ ...newTweet, url: e.target.value })}
                placeholder="https://twitter.com/username/status/..."
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500"
              />
            </div>

            <button
              onClick={addTweet}
              className="w-full px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
            >
              Add Tweet
            </button>
          </div>
        </div>
      )}

      {tweets.length === 0 ? (
        <div className="text-center py-12 bg-gray-50 rounded-lg border-2 border-dashed border-gray-300">
          <p className="text-gray-500 text-lg">No tweets added yet</p>
          <p className="text-gray-400 text-sm mt-2">
            Click &quot;Add Tweet&quot; to start tracking your top performers
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {tweets.map((tweet, index) => (
            <div
              key={tweet.id}
              className="p-5 bg-white rounded-lg border border-gray-200 shadow-sm hover:shadow-md transition-shadow"
            >
              <div className="flex justify-between items-start mb-3">
                <div className="flex items-center gap-2">
                  <span className="text-sm font-semibold text-blue-600">
                    Tweet #{index + 1}
                  </span>
                  <span className="text-xs text-gray-500">{tweet.date}</span>
                </div>
                <button
                  onClick={() => removeTweet(tweet.id)}
                  className="text-red-500 hover:text-red-700 text-sm font-medium"
                >
                  Remove
                </button>
              </div>

              <p className="text-gray-800 mb-4 whitespace-pre-wrap">{tweet.text}</p>

              <div className="flex flex-wrap gap-4 text-sm">
                <div className="flex items-center gap-1">
                  <span>♥</span>
                  <span className="font-medium">{tweet.likes.toLocaleString()}</span>
                  <span className="text-gray-500">likes</span>
                </div>
                <div className="flex items-center gap-1">
                  <span>⟳</span>
                  <span className="font-medium">{tweet.retweets.toLocaleString()}</span>
                  <span className="text-gray-500">retweets</span>
                </div>
                <div className="flex items-center gap-1">
                  <span>💬</span>
                  <span className="font-medium">{tweet.replies.toLocaleString()}</span>
                  <span className="text-gray-500">replies</span>
                </div>
                {tweet.impressions && (
                  <>
                    <div className="flex items-center gap-1">
                      <span>👁</span>
                      <span className="font-medium">
                        {tweet.impressions.toLocaleString()}
                      </span>
                      <span className="text-gray-500">impressions</span>
                    </div>
                    <div className="flex items-center gap-1">
                      <span>📊</span>
                      <span className="font-medium">
                        {calculateEngagementRate(tweet)}
                      </span>
                      <span className="text-gray-500">engagement</span>
                    </div>
                  </>
                )}
              </div>

              {tweet.url && (
                <a
                  href={tweet.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-500 hover:text-blue-700 text-sm mt-3 inline-block"
                >
                  View on Twitter →
                </a>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
