"use client"

import { memo, useState } from "react"
import { Handle, Position, Node } from "@xyflow/react"
import { MessageContent } from "@/components/prompt-kit/message"
import { Button } from "@/components/ui/button"
import { Copy, Download, Check, Coins } from "lucide-react"
import { DotsLoader } from "@/components/prompt-kit/loader"
import jsPDF from "jspdf"

export interface ResultNodeData extends Record<string, unknown> {
  content: string
  isLoading?: boolean
  useCaseTitle?: string
  onMintNFT?: (content: string) => void
}

export type ResultNodeType = Node<ResultNodeData, "result">

const ResultNode = memo(({ data }: { data: ResultNodeData }) => {
  const [copied, setCopied] = useState(false)
  const [isExporting, setIsExporting] = useState(false)

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(data.content)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error("Failed to copy:", err)
    }
  }

  const exportToPDF = async () => {
    if (!data.content) return

    setIsExporting(true)
    try {
      const pdf = new jsPDF("p", "mm", "a4")
      const pageWidth = pdf.internal.pageSize.getWidth()
      const pageHeight = pdf.internal.pageSize.getHeight()
      const margin = 20
      const contentWidth = pageWidth - 2 * margin
      let yPosition = margin

      // Title
      pdf.setFontSize(22)
      pdf.setFont("helvetica", "bold")
      pdf.text(data.useCaseTitle || "AI Generated Result", margin, yPosition)
      yPosition += 12

      // Date
      pdf.setFontSize(10)
      pdf.setFont("helvetica", "normal")
      pdf.setTextColor(100, 100, 100)
      pdf.text(`Generated on ${new Date().toLocaleString()}`, margin, yPosition)
      yPosition += 15

      // Content
      pdf.setFontSize(11)
      pdf.setFont("helvetica", "normal")
      pdf.setTextColor(0, 0, 0)

      // Split content into lines
      const lines = pdf.splitTextToSize(data.content, contentWidth)

      for (let i = 0; i < lines.length; i++) {
        // Check if we need a new page
        if (yPosition > pageHeight - margin - 15) {
          pdf.addPage()
          yPosition = margin
        }
        pdf.text(lines[i], margin, yPosition)
        yPosition += 6
      }

      // Footer on all pages
      const pageCount = pdf.internal.pages.length - 1
      for (let i = 1; i <= pageCount; i++) {
        pdf.setPage(i)
        pdf.setFontSize(8)
        pdf.setTextColor(150, 150, 150)
        pdf.text(
          `Page ${i} of ${pageCount}`,
          pageWidth / 2,
          pageHeight - 10,
          { align: "center" }
        )
        pdf.text(
          "Generated by xcampBanana - AI Brand Kit Planner",
          margin,
          pageHeight - 10
        )
      }

      const fileName = `${(data.useCaseTitle || "ai-result").toLowerCase().replace(/\s+/g, "-")}-${new Date().toISOString().split("T")[0]}.pdf`
      pdf.save(fileName)
    } catch (error) {
      console.error("PDF export error:", error)
      alert("Failed to export PDF. Please try again.")
    } finally {
      setIsExporting(false)
    }
  }

  return (
    <div className="rounded-xl border-2 border-green-400 bg-gradient-to-br from-green-50 to-white shadow-xl p-5 min-w-[450px] max-w-[550px]">
      <Handle type="target" position={Position.Left} className="!bg-green-500" />

      <div className="mb-3 flex items-center justify-between">
        <h3 className="text-sm font-semibold text-green-700">
          AI Generated Result
        </h3>
        {!data.isLoading && data.content && (
          <div className="flex gap-1">
            <Button
              variant="ghost"
              size="icon"
              className="h-7 w-7 rounded-full"
              onClick={copyToClipboard}
              title="Copy to clipboard"
            >
              {copied ? <Check size={14} className="text-green-600" /> : <Copy size={14} />}
            </Button>
          </div>
        )}
      </div>

      <div className="prose prose-sm max-w-none mb-4">
        {data.isLoading ? (
          <div className="flex items-center gap-3 py-4">
            <DotsLoader />
            <span className="text-sm text-gray-500">Generating result...</span>
          </div>
        ) : data.content ? (
          <div className="max-h-[400px] overflow-y-auto pr-2">
            <MessageContent markdown className="text-gray-800">
              {data.content}
            </MessageContent>
          </div>
        ) : (
          <div className="text-gray-400 text-center py-8">
            <p className="text-sm">Result will appear here after generation</p>
          </div>
        )}
      </div>

      {!data.isLoading && data.content && (
        <div className="flex gap-2 pt-3 border-t border-green-200">
          <Button
            onClick={exportToPDF}
            disabled={isExporting}
            variant="outline"
            size="sm"
            className="flex-1 border-green-300 text-green-700 hover:bg-green-50"
          >
            <Download size={14} className="mr-2" />
            {isExporting ? "Exporting..." : "Export to PDF"}
          </Button>
          {data.onMintNFT && (
            <Button
              onClick={() => data.onMintNFT?.(data.content)}
              variant="outline"
              size="sm"
              className="flex-1 border-orange-300 text-orange-700 hover:bg-orange-50"
            >
              <Coins size={14} className="mr-2" />
              Mint as NFT
            </Button>
          )}
        </div>
      )}
    </div>
  )
})

ResultNode.displayName = "ResultNode"

export default ResultNode
